name: Jobs Check
on:
  pull_request:
    types:
     #- opened
     #- synchronize
     - closed
    branches:
     - main  
     
  workflow_dispatch:  
  
jobs:  
    on_merged:    
      if: github.base_ref == 'main' && github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
         - name: Echo base_ref
           run: |
             echo ${{ github.base_ref }}
         - name: Echo head_ref
           run: |
             echo ${{  github.head_ref }}
         - name: Echo ref
           run: |
             echo ${{  github. github.ref }}
